import os
BASE_DIR = r"c:\Users\abhignya\Downloads\my-smart-beat-main\my-smart-beat-main"
ROUTES_DIR = os.path.join(BASE_DIR, "src", "routes")

pages = {
    "index.tsx": """import { createFileRoute, Link } from '@tanstack/react-router';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Activity, ShieldAlert, Zap, BarChart3, Bot, Database, Cpu } from "lucide-react";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute('/')({
  component: Dashboard,
});

function Dashboard() {
  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">SmartHome Analytics Dashboard</h1>
        <p className="text-muted-foreground mt-2">Privacy-Preserving Machine Learning for Household Intelligence.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Dataset Status</CardTitle>
            <Database className="size-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">125,430</div>
            <p className="text-xs text-muted-foreground">Rows analyzed</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Routine Consistency</CardTitle>
            <BarChart3 className="size-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">87%</div>
            <p className="text-xs text-muted-foreground">Historical pattern match</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Anomalies</CardTitle>
            <ShieldAlert className="size-4 text-orange-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-orange-600">7 Detected</div>
            <p className="text-xs text-muted-foreground">Awaiting review</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Peak Energy</CardTitle>
            <Zap className="size-4 text-blue-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-blue-600">4.8 kW</div>
            <p className="text-xs text-muted-foreground">Forecast: 3.1 kW next hr</p>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Welcome to SmartHome AI</CardTitle>
            <CardDescription>User Journey Outline</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <ol className="list-decimal ml-4 space-y-2 text-sm">
              <li><b>Upload Dataset:</b> Navigate to Data Ingestion.</li>
              <li><b>Validate:</b> Inspect in Dataset Explorer.</li>
              <li><b>Analyze:</b> Run Activity Recognition & Routine Discovery.</li>
              <li><b>Secure:</b> Check Anomaly Detection for safety.</li>
              <li><b>Optimize:</b> View Energy Intelligence & Appliances.</li>
              <li><b>Query:</b> Ask the AI Assistant for insights.</li>
            </ol>
            <Button asChild className="w-full mt-4"><Link to="/ingestion">Start Data Ingestion</Link></Button>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2"><Bot className="size-5" /> AI Insights Summary</CardTitle>
            <CardDescription>Generated by the Analyst Assistant</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="bg-muted p-4 rounded-md text-sm space-y-2">
              <p>• <b>Energy:</b> The AC unit is responsible for 42% of total peak load.</p>
              <p>• <b>Routine:</b> Dinner usually begins around 8:14 PM with high consistency.</p>
              <p>• <b>Safety:</b> An unusual appliance event was detected at 3:12 AM.</p>
              <p>• <b>Optimization:</b> Shifting heavy appliance usage to post-9PM could reduce peak demand by 15%.</p>
            </div>
            <Button variant="outline" asChild className="w-full mt-4"><Link to="/assistant">Ask AI Assistant</Link></Button>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
""",
    "ingestion.tsx": """import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { UploadCloud, CheckCircle2, FileText, Activity, AlertTriangle } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";

export const Route = createFileRoute("/ingestion")({
  component: DataIngestion,
});

function DataIngestion() {
  const [file, setFile] = useState<File | null>(null);
  const [step, setStep] = useState(1);
  const [isProcessing, setIsProcessing] = useState(false);
  const [dataScore, setDataScore] = useState(94);

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const uploadedFile = e.target.files?.[0];
    if (!uploadedFile) return;
    setFile(uploadedFile);
    setStep(2);
    setIsProcessing(true);
    setTimeout(() => {
        setIsProcessing(false);
        setStep(3);
        toast.success("Data successfully extracted & validated.");
    }, 2000);
  };

  const loadDemo = () => {
    setIsProcessing(true);
    setTimeout(() => {
      setFile(new File([], "demo_smarthome_data.csv"));
      setIsProcessing(false);
      setStep(3);
      toast.success("Demo Dataset Loaded");
    }, 1000);
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Data Ingestion</h1>
          <p className="text-muted-foreground mt-2">Upload raw household data to begin the ML pipeline.</p>
        </div>
        <Button variant="outline" onClick={loadDemo}>Load Demo Dataset</Button>
      </div>

      {step <= 2 && (
        <Card className="border-dashed border-2 bg-muted/20">
          <CardContent className="flex flex-col items-center justify-center p-12 text-center space-y-4">
            <div className="rounded-full bg-primary/10 p-4">
              <UploadCloud className="size-8 text-primary" />
            </div>
            <div className="space-y-1">
              <h3 className="font-semibold text-lg">Upload Your Dataset</h3>
              <p className="text-sm text-muted-foreground max-w-sm">
                Drag & Drop your file here, or click to browse.
              </p>
            </div>
            <div className="flex gap-2">
              <Badge variant="secondary">CSV</Badge>
              <Badge variant="secondary">XLSX</Badge>
              <Badge variant="secondary">PDF</Badge>
            </div>
            <div className="mt-6 relative">
              <Button disabled={isProcessing}>
                {isProcessing ? "Validating & Preprocessing..." : "Choose File"}
              </Button>
              <input type="file" className="absolute inset-0 w-full h-full opacity-0 cursor-pointer" accept=".csv,.xlsx,.xls,.pdf" onChange={handleFileUpload} disabled={isProcessing} />
            </div>
          </CardContent>
        </Card>
      )}

      {step === 3 && (
        <div className="space-y-6 animate-in slide-in-from-bottom-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2"><CheckCircle2 className="text-green-500" /> Preprocessing Pipeline Complete</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
                <div><p className="text-sm text-muted-foreground">Dataset</p><p className="font-bold truncate">{file?.name}</p></div>
                <div><p className="text-sm text-muted-foreground">Rows</p><p className="font-bold">125,430</p></div>
                <div><p className="text-sm text-muted-foreground">Columns</p><p className="font-bold">18</p></div>
                <div><p className="text-sm text-muted-foreground">Data Quality Score</p><p className="font-bold text-green-600">{dataScore}%</p></div>
              </div>

              <div className="space-y-3">
                <div className="flex justify-between items-center text-sm border-b pb-2"><span>Timestamp Column</span><Badge className="bg-green-100 text-green-800 hover:bg-green-100">Detected</Badge></div>
                <div className="flex justify-between items-center text-sm border-b pb-2"><span>Energy Columns</span><Badge className="bg-green-100 text-green-800 hover:bg-green-100">Detected</Badge></div>
                <div className="flex justify-between items-center text-sm border-b pb-2"><span>Motion Sensors</span><Badge className="bg-green-100 text-green-800 hover:bg-green-100">Detected</Badge></div>
                <div className="flex justify-between items-center text-sm border-b pb-2"><span>Missing Values</span><Badge variant="outline">Handled (Imputed)</Badge></div>
                <div className="flex justify-between items-center text-sm border-b pb-2"><span>Temporal Features</span><Badge variant="outline">Generated</Badge></div>
              </div>
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  );
}
""",
    "explorer.tsx": """import { createFileRoute } from "@tanstack/react-router";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from "recharts";

export const Route = createFileRoute("/explorer")({
  component: DatasetExplorer,
});

const sampleData = [
  { time: "06:00", power: 0.8, room: "Bedroom", motion: "ON" },
  { time: "07:30", power: 3.2, room: "Kitchen", motion: "ON" },
  { time: "09:00", power: 1.1, room: "Living", motion: "OFF" },
  { time: "12:00", power: 1.4, room: "Kitchen", motion: "ON" },
  { time: "18:00", power: 4.5, room: "Living", motion: "ON" },
];

const chartData = [
  { name: 'Mon', energy: 12 }, { name: 'Tue', energy: 15 }, { name: 'Wed', energy: 14 },
  { name: 'Thu', energy: 18 }, { name: 'Fri', energy: 16 }, { name: 'Sat', energy: 22 }, { name: 'Sun', energy: 24 }
];

function DatasetExplorer() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Dataset Explorer</h1>
        <p className="text-muted-foreground mt-2">Inspect the uploaded schema and feature engineering results.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Feature Engineering Pipeline</CardTitle>
            <CardDescription>Generated features ready for ML</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              <span className="bg-blue-100 text-blue-800 text-xs px-2 py-1 rounded">Hour</span>
              <span className="bg-blue-100 text-blue-800 text-xs px-2 py-1 rounded">Day of Week</span>
              <span className="bg-blue-100 text-blue-800 text-xs px-2 py-1 rounded">Weekend Indicator</span>
              <span className="bg-purple-100 text-purple-800 text-xs px-2 py-1 rounded">Rolling Energy (1h)</span>
              <span className="bg-purple-100 text-purple-800 text-xs px-2 py-1 rounded">Power Change Delta</span>
              <span className="bg-green-100 text-green-800 text-xs px-2 py-1 rounded">Time Since Prev Event</span>
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader>
            <CardTitle>Daily Energy Trends</CardTitle>
          </CardHeader>
          <CardContent className="h-[150px]">
             <ResponsiveContainer width="100%" height="100%">
                <BarChart data={chartData}>
                  <XAxis dataKey="name" fontSize={12} tickLine={false} axisLine={false} />
                  <Tooltip />
                  <Bar dataKey="energy" fill="#3b82f6" radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Data Preview (First 5 Rows)</CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Timestamp</TableHead>
                <TableHead>Total Power (kW)</TableHead>
                <TableHead>Active Room</TableHead>
                <TableHead>Motion Sensor</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {sampleData.map((row, i) => (
                <TableRow key={i}>
                  <TableCell>{row.time}</TableCell>
                  <TableCell>{row.power}</TableCell>
                  <TableCell>{row.room}</TableCell>
                  <TableCell>{row.motion}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
"""
}

for filename, content in pages.items():
    with open(os.path.join(ROUTES_DIR, filename), "w") as f:
        f.write(content)
print("Step 2 completed.")

