import { createFileRoute, Link } from '@tanstack/react-router';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Activity, ShieldAlert, Zap, BarChart3, Bot, Database, Cpu } from "lucide-react";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute('/')({
  component: Dashboard,
});

function Dashboard() {
  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">SmartHome Analytics Dashboard</h1>
        <p className="text-muted-foreground mt-2">Privacy-Preserving Machine Learning for Household Intelligence.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Dataset Status</CardTitle>
            <Database className="size-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">125,430</div>
            <p className="text-xs text-muted-foreground">Rows analyzed</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Routine Consistency</CardTitle>
            <BarChart3 className="size-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">87%</div>
            <p className="text-xs text-muted-foreground">Historical pattern match</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Anomalies</CardTitle>
            <ShieldAlert className="size-4 text-orange-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-orange-600">7 Detected</div>
            <p className="text-xs text-muted-foreground">Awaiting review</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Peak Energy</CardTitle>
            <Zap className="size-4 text-blue-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-blue-600">4.8 kW</div>
            <p className="text-xs text-muted-foreground">Forecast: 3.1 kW next hr</p>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Welcome to SmartHome AI</CardTitle>
            <CardDescription>User Journey Outline</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <ol className="list-decimal ml-4 space-y-2 text-sm">
              <li><b>Upload Dataset:</b> Navigate to Data Ingestion.</li>
              <li><b>Validate:</b> Inspect in Dataset Explorer.</li>
              <li><b>Analyze:</b> Run Activity Recognition & Routine Discovery.</li>
              <li><b>Secure:</b> Check Anomaly Detection for safety.</li>
              <li><b>Optimize:</b> View Energy Intelligence & Appliances.</li>
              <li><b>Query:</b> Ask the AI Assistant for insights.</li>
            </ol>
            <Button asChild className="w-full mt-4"><Link to="/ingestion">Start Data Ingestion</Link></Button>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2"><Bot className="size-5" /> AI Insights Summary</CardTitle>
            <CardDescription>Generated by the Analyst Assistant</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="bg-muted p-4 rounded-md text-sm space-y-2">
              <p>• <b>Energy:</b> The AC unit is responsible for 42% of total peak load.</p>
              <p>• <b>Routine:</b> Dinner usually begins around 8:14 PM with high consistency.</p>
              <p>• <b>Safety:</b> An unusual appliance event was detected at 3:12 AM.</p>
              <p>• <b>Optimization:</b> Shifting heavy appliance usage to post-9PM could reduce peak demand by 15%.</p>
            </div>
            <Button variant="outline" asChild className="w-full mt-4"><Link to="/assistant">Ask AI Assistant</Link></Button>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
