/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AnomaliesRouteImport } from './routes/anomalies'
import { Route as ApplianceRouteImport } from './routes/appliance'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as EnergyRouteImport } from './routes/energy'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as RoutineRouteImport } from './routes/routine'
import { Route as SensorsRouteImport } from './routes/sensors'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomaliesRoute = AnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplianceRoute = ApplianceRouteImport.update({
  id: '/appliance',
  path: '/appliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyRoute = EnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineRoute = RoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsRoute = SensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/anomalies': typeof AnomaliesRoute
  '/appliance': typeof ApplianceRoute
  '/assistant': typeof AssistantRoute
  '/energy': typeof EnergyRoute
  '/models': typeof ModelsRoute
  '/plan': typeof PlanRoute
  '/routine': typeof RoutineRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/anomalies': typeof AnomaliesRoute
  '/appliance': typeof ApplianceRoute
  '/assistant': typeof AssistantRoute
  '/energy': typeof EnergyRoute
  '/models': typeof ModelsRoute
  '/plan': typeof PlanRoute
  '/routine': typeof RoutineRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/anomalies': typeof AnomaliesRoute
  '/appliance': typeof ApplianceRoute
  '/assistant': typeof AssistantRoute
  '/energy': typeof EnergyRoute
  '/models': typeof ModelsRoute
  '/plan': typeof PlanRoute
  '/routine': typeof RoutineRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/anomalies'
    | '/appliance'
    | '/assistant'
    | '/energy'
    | '/models'
    | '/plan'
    | '/routine'
    | '/sensors'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/anomalies'
    | '/appliance'
    | '/assistant'
    | '/energy'
    | '/models'
    | '/plan'
    | '/routine'
    | '/sensors'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/anomalies'
    | '/appliance'
    | '/assistant'
    | '/energy'
    | '/models'
    | '/plan'
    | '/routine'
    | '/sensors'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AnomaliesRoute: typeof AnomaliesRoute
  ApplianceRoute: typeof ApplianceRoute
  AssistantRoute: typeof AssistantRoute
  EnergyRoute: typeof EnergyRoute
  ModelsRoute: typeof ModelsRoute
  PlanRoute: typeof PlanRoute
  RoutineRoute: typeof RoutineRoute
  SensorsRoute: typeof SensorsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomalies': {
      id: '/anomalies'
      path: '/anomalies'
      fullPath: '/anomalies'
      preLoaderRoute: typeof AnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appliance': {
      id: '/appliance'
      path: '/appliance'
      fullPath: '/appliance'
      preLoaderRoute: typeof ApplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy': {
      id: '/energy'
      path: '/energy'
      fullPath: '/energy'
      preLoaderRoute: typeof EnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine': {
      id: '/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof RoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors': {
      id: '/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof SensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AnomaliesRoute: AnomaliesRoute,
  ApplianceRoute: ApplianceRoute,
  AssistantRoute: AssistantRoute,
  EnergyRoute: EnergyRoute,
  ModelsRoute: ModelsRoute,
  PlanRoute: PlanRoute,
  RoutineRoute: RoutineRoute,
  SensorsRoute: SensorsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
