/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AnomaliesRouteImport } from './routes/anomalies'
import { Route as AppliancesRouteImport } from './routes/appliances'
import { Route as ChangesRouteImport } from './routes/changes'
import { Route as EnergyRouteImport } from './routes/energy'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as IngestionRouteImport } from './routes/ingestion'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as RoutineRouteImport } from './routes/routine'
import { Route as TimelineRouteImport } from './routes/timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomaliesRoute = AnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => rootRouteImport,
} as any)
const AppliancesRoute = AppliancesRouteImport.update({
  id: '/appliances',
  path: '/appliances',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesRoute = ChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyRoute = EnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestionRoute = IngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineRoute = RoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/anomalies': typeof AnomaliesRoute
  '/appliances': typeof AppliancesRoute
  '/changes': typeof ChangesRoute
  '/energy': typeof EnergyRoute
  '/evaluation': typeof EvaluationRoute
  '/explorer': typeof ExplorerRoute
  '/ingestion': typeof IngestionRoute
  '/predictions': typeof PredictionsRoute
  '/routine': typeof RoutineRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/anomalies': typeof AnomaliesRoute
  '/appliances': typeof AppliancesRoute
  '/changes': typeof ChangesRoute
  '/energy': typeof EnergyRoute
  '/evaluation': typeof EvaluationRoute
  '/explorer': typeof ExplorerRoute
  '/ingestion': typeof IngestionRoute
  '/predictions': typeof PredictionsRoute
  '/routine': typeof RoutineRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/anomalies': typeof AnomaliesRoute
  '/appliances': typeof AppliancesRoute
  '/changes': typeof ChangesRoute
  '/energy': typeof EnergyRoute
  '/evaluation': typeof EvaluationRoute
  '/explorer': typeof ExplorerRoute
  '/ingestion': typeof IngestionRoute
  '/predictions': typeof PredictionsRoute
  '/routine': typeof RoutineRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/anomalies'
    | '/appliances'
    | '/changes'
    | '/energy'
    | '/evaluation'
    | '/explorer'
    | '/ingestion'
    | '/predictions'
    | '/routine'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/anomalies'
    | '/appliances'
    | '/changes'
    | '/energy'
    | '/evaluation'
    | '/explorer'
    | '/ingestion'
    | '/predictions'
    | '/routine'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/anomalies'
    | '/appliances'
    | '/changes'
    | '/energy'
    | '/evaluation'
    | '/explorer'
    | '/ingestion'
    | '/predictions'
    | '/routine'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AnomaliesRoute: typeof AnomaliesRoute
  AppliancesRoute: typeof AppliancesRoute
  ChangesRoute: typeof ChangesRoute
  EnergyRoute: typeof EnergyRoute
  EvaluationRoute: typeof EvaluationRoute
  ExplorerRoute: typeof ExplorerRoute
  IngestionRoute: typeof IngestionRoute
  PredictionsRoute: typeof PredictionsRoute
  RoutineRoute: typeof RoutineRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomalies': {
      id: '/anomalies'
      path: '/anomalies'
      fullPath: '/anomalies'
      preLoaderRoute: typeof AnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appliances': {
      id: '/appliances'
      path: '/appliances'
      fullPath: '/appliances'
      preLoaderRoute: typeof AppliancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes': {
      id: '/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy': {
      id: '/energy'
      path: '/energy'
      fullPath: '/energy'
      preLoaderRoute: typeof EnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingestion': {
      id: '/ingestion'
      path: '/ingestion'
      fullPath: '/ingestion'
      preLoaderRoute: typeof IngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine': {
      id: '/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof RoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AnomaliesRoute: AnomaliesRoute,
  AppliancesRoute: AppliancesRoute,
  ChangesRoute: ChangesRoute,
  EnergyRoute: EnergyRoute,
  EvaluationRoute: EvaluationRoute,
  ExplorerRoute: ExplorerRoute,
  IngestionRoute: IngestionRoute,
  PredictionsRoute: PredictionsRoute,
  RoutineRoute: RoutineRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
